name: Build Docker Image
on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 1 * *'
jobs:
  build:
    strategy:
      matrix:
        scheme: [small, full]
    name: Build TeXLive [${{ matrix.scheme }}-scheme]
    runs-on: ubuntu-latest
    env:
      SCHEME: ${{ matrix.scheme }}
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v1
      - name: Build
        run: |
          docker build -t texlive-$SCHEME --build-arg scheme=$SCHEME .
      - name: Test
        run: |
          docker run --rm texlive-$SCHEME pdflatex --version
      - name: Deploy
        run: |
          set -e
          docker login docker.pkg.github.com -p "$GITHUB_TOKEN"
          TAG="docker.pkg.github.com/$GITHUB_REPOSITORY/texlive-$SCHEME"
          VERSION="$(date "+%Y%m%d")"
          docker tag texlive-$SCHEME $TAG:$VERSION
          docker tag texlive-$SCHEME $TAG:latest
          docker images
          #docker push $TAG
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: github.ref == 'refs/heads/master'
